language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  api_key:
    secure: Gptf/ocOC9+otqDmUcXIGJQRUAzVCe6m7ECHY3vCG69XM/SSgFiXPLioz6qWrzRJzOivg1oDWD2jnRnJPWDH5U2CYXK1V+kFltQznFStqU+XuOedtDb/A1qYrI/r0LIDblW0WzrYDKqQchwHnT6Qz0V6CeOMxlbBwXi335itE3vKt2t89CqcISIOLIRn5XElr2FsQN5bHbYWk18IwI2TJx9FTcAalKEF4XL5I2tVtheARtQDYG9BDvr8v1xfJFmez2+9ah2aoMq5giQmZHGpQ2qY23Nf/LrojGJx9H6Xa19Sq+Rr/pVgAsEPwkqNyFULOHlu5TPBnv+kD930M5eMQKdEAcXFnCydrDSohxaM74n2+u9EOkclT3iPkqnnLbChLY39seFn7N+TT57k9I5xK1ERK/Sqi2qfACKJ6WlXchTa1m08FmaMFcaV/PcI3UbOioirYsH+hp0J8EqBNTFHztBaeZDEJ2YaQ37OVAcxYEa1g9iK9/sYOoB6cj0jTwYYdPoNnbKdEou49e1Gablz4ZWggnz4i0BHCxl+Pei2EcNtE1843cbM9y8RHvlwoVaUsV5Rl+TLe7jL7mhqrJNkKe+AS/oI5o974xYDo8vsV4FVDp1G0ncVkLCimSc1Odm5Pp+QfaOjhA0YodpxIY1vehP8wr2T+CVCr2FGb95XGh4=
  on:
    tags: true
    repo: mozilla/potools
