language: node_js
sudo: false
node_js:
- 8
- 10
script: yarn test-ci
cache: yarn
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  api_key:
    secure: vXTr7xLZCedaEmXmnB5tqYtrE9v9dE5ahbtMEGBpYzmPoxFQ7fz/a46g/9OLHxzLzDSaJOlAY1nD4HOqmz1YMRbUSl3UZL/RckIqO/3Ji4+k7cFkxLnJpeALLSqPZHkPap2Vo29tmkK7IxdvW84yvVv2F9odGrQlFiZntEwta/9CdEJmDWCrUT/5ODGCVD/pmlkeTw3/F0amFE7KA5cNmGD3mcQ6BcIm5pip3o6ftdud1ej9GJY+ZJpica8w9RoNZY4RTF7ZnwHXjdDnWMIwHuxu8gfBZ5sPrmaRzH5uW3mBkfXUNtVvIViFPcTLvllPYqTO51zqYE4jrV6RQmUf9YO5/ft51xuAYgaXyqQ5Vo62ctpPd/wyxlhXlKlmsdnJcyrFaPhBAI9eVjR2mIhcY9SE9yGZitq7Ykm8t6YCfV7XlXXgTjnxQSOFyFeR5JpfiT0qIuxG2HLQYiYztjrf9F0p6o5LpemBgm7n00rrsRDLxxazpqCPVQ/JTPsELObI6+Ta0KcTGxnJvcEjUnJ1MUv62BnUMh5j2MbYXS2R3Ik99U+7EJmq9yozEFpmiNLtOnuJ2EkjRfGE04jZWlbLznT3dM7YdZA5/TmmT5falGvrxcqa9yPGlnLYJsPEOob0OTf5qu33t2Vgq2UMO1FVKr61poVEmV3jyD3uz4yo21g=
  on:
    tags: true
    repo: mozilla/potools
